### ISSUE TITLE
Идеи для метро от Грэнта

### ISSUE THREAD

**Issue by NicholayGrant** [bossobeboss/newmetro#1]
123

**Comment by NicholayGrant** [comment]
1) Добавить новые профессии для ВДНХ -
1.1) Медик ВДНХ (есть лазарет, медика нет)
1.2) Обновить снаряжение для смотрителей ВДНХ, ублюдок, серьезно?
1.2.1) Начальник ВДНХ - убрать револьвер, и выдать примерно ублюдка, для экстр. случая и падонок.
1.2.2) Смотритель ВДНХ - добавить 45 брони, убрать ублюдок и дать на замену АКС-74У, возможно заменить скин.
1.2.3) Медик - падонок, 3 обоймы, скин с +, я там  кину если отпишут в ЛС или сюда.
1.2.4) Нач.Охраны ВДНХ - 65 брони, АК-74, 4 обоймы, хорошую броню.
1.2.5) Джаггернаут ВДНХ - хорошая броня (110), скин соотвествующий, у меня есть вроде, гатлинг.
1.2.6) Уборщик ВДНХ - без оружия, метлу добавить.
2) На станциях добавить генераторы, которые надо будет заправлять добываемыми материалами, типо дерева, либо работает/не работает.
3) Добавить разные профессии, потипу - админ, хелпер, и запретить свой /job, т.к многие пишут ху*ню в джоб, "Наемник" не нужный, не по лору, добавить профессии разные к другим профессиям, лидер шайки бандитов.
4) Если нет электричества - нет открытию гермоворот, все по РП, можно подключить авар. питание, где будет красный свет гореть у гермоворот.
5) Ужесточить сис-му еды, сделать её огр. кол-во, если человек недоедает - теряет сознание и немного ХП.
Будет добавляться

**Comment by Gribnik228** [comment]
123

**Comment by bossobeboss** [comment]
1. Думаю профессии добавим.
2. Мб.
3. Будут.
4. К сожалению не сможем.
5. Подумаем
_________________________________
Когда все идеи будут выполнены/отклонены мы напишем в данную тему

**Comment by NicholayGrant** [comment]
6) Убрать экзоскелеты и заменить их на нормальные скины с броней.
7) Сделать больше раз взлома дверей дробовиком.
8) Сделать новые станции.
9) Добавить больше оружия, больше брони у торговца.
10) Добавь шкалу усталости, т.к у Вас бесконечно бегай.
БУДЕТ ДОБАВЛЯТЬСЯ
