### ISSUE TITLE
Идеи от Андрея Че

### ISSUE THREAD

**Issue by And-rey-Che** [bossobeboss/newmetro#11]
1) Оруженая составляющая.
1.1. Добавить автоматам возможность стрелять патронами-деньгами (не знаю, каким образом), урон +15% или +30%. В крайних случаях, думаю неплохой бонус.
1.2. Добавить оружейные модули в качестве лута, убрать оружия с модулями из меню покупки, оставив только классические. Добавить возможность ставить планки (также лутаемо) для прицелов на верстаке (и получить, например, АК с обвесами).
1.3. Добавить возможность крафтить рельсу из электроники и прочей лутаемой херни.
1.4. Добавить гранаты-динамиты и метательные ножи.
1.5. Добавить трехзарядный гранатомет как в DLC Рейх (стреляет гранатами дальше, чем перс).
1.6. Добавить флаеры для подсвета туннелей, как ракетница handz, но без дамага и ярче светящиеся.

**Comment by bossobeboss** [comment]
Ми попробуем. Ожидайте отвит.
