### ISSUE TITLE
ИДЕЯ #3

### ISSUE THREAD

**Issue by NicholayGrant** [bossobeboss/newmetro#12]
1) Ввести новые рации, которые могут управляться голосом так и чатом, рация будет появлятся в слотах и когда нажал "Активировать", то можешь написать в чат и будет перетранслировано по рации и так-же голос, т.к за*бали "/advert [Рация КЛ] Красная линия, всем построится на базе!", и так далее.
2) Добавить перегрев, клин оружий, поломку, распределить урон, бронепробиваемость оружий, настроить под правильный урон, т.к с фаланги(не лорная, которой даже в игре нет), легко пробить разные виды брони, и с ДШК и все так далее, понимаю ради доната, но надо ведь и использовать обычные оружия.
3) Полная кастомизация персонажа. Для этого можно использовать PAC3, ставить шлемы на головы, бронижелеты, сделать его военным, жителем с шапкой и очками, и разными обьектами из метро, что добавить реалестичность! (Можно коллекцию аддонов для PAC3 сделать в слоте, дабы не шастать)
4) Попал в руку? - упало оружие, и ты врядли сможешь его взять! Попал в голову? - получай верную смерть. Попал в ногу? - ходи очень медленно. Попал в грудь? - повезло тебе, кровопотеря. 
5) За*бало жать на альт? Поставить аддон на автоматическую медленную ходьбу, Волк, обновляй коллекцию!
6) Добавить ножи и так далее, дабы самооборонятся, а не какой-то еб*ный лом!
7) Сломался противогаз? Держи двойную потерю кислорода!
8) Оживить Красную Линию и 4 рейх, добавить им жилые комплексы! А то на ВДНХ живи, а на КЛ и Рейх нет? 
9) Много еррор текстур, предлагаю их просто заблокировать, а если популярные пропы еррорные - установи контент Half Life и т.д, после чего должны пропасть, как было у меня!

Обязательно дополню!

**Comment by bossobeboss** [comment]
1. Хз.
2. Возможно. Не знаю.
3. Иди ты со своим ПАКом. Если и сделаем то не так.
4. Игроки от этого не будут в восторге.
5. Какая коллекция какой альт. Какая ходьба.
6. Думаю да.
7. Какая потеря кислорода.
8. Попробуем
9. У меня фулл контент.
_________________________________
Когда все идеи будут выполнены/отклонены мы напишем в данную тему. Апдейты в новую тему пиши.
