### ISSUE TITLE
Идеи намбер файф.

### ISSUE THREAD

**Issue by NicholayGrant** [bossobeboss/newmetro#13]
1) Добавить разные виды брони, так-же добавить наконец анимации, т.к нулевая поза при ходьбе не очень выглядит.
2) Добавить грибной чай, и так-же самостоятельное изготовление этого чая, желательно не в верстаке. Прибавит к атмосфере +.
3) Есть костры, но нет возможности подогреть холодную пищу, почему? Предлагаю добавить в костре пункты - подогреть еду, и будет появляться только подогрев нужной еды(которая в инвентаре), и она будет давать свои бонусы! (Т.к одно жареное мясо, не кайф).
4) Не знаю, было ли предложение о жажде, и так далее. Предлагаю ввести - жажду, температуру тела, сытость, усталость и так-же разные заболевания, например, поднятие температуры и так далее, от которой например нужно долго избавлятся с помощью чая и так далее.
5) Возможность взять, лечь и стрелять, в воркшопе есть такой аддон.
6) Возможность обычному человеку взять, и разжечь костер! Возможность добавлять в костер разный мусор, дабы увеличить на секунды горение костра! Находишь дрова в метро, если есть 4-5 штук - разжигай костер!
7) Новый лут! Предлагаю в лут добавить : оружие, ведь ходя по поверхности, у многих трупов можно было найти оружие! Противогаз, аптечки, патроны и многое другое!
8) Добавить призраков, которые появлялись в вагонах при прохождении кампании, было бы очень круто и атмосферно, когда в разное время в разных местах появляется этот дух.
9) Добавить трассеры пуль, т.к в темных местах, пули бывают отсвечиваются, так-что можно добавить.
10) Я тебе Илья уже скидывал аддон, где идет фикс фонаря, т.е можно видеть куда именно светит фонарь, а не какой-то луч из руки. 
11) Лень ставить PAC3? - поинтшоп, с возможностью обставить своего персонажа вещами, играя просто на сервере. (С лимитом конечно-же)

**Comment by bossobeboss** [comment]
1. Ты блядь понимаешь что это только у тех кто дохуя накачал как ты контента, если только с нашим играть 0 позы не будет, твой косяк.
2. Возможно да.
3. Оке.
4. Ой иди ты такого не будет и не было в метро.
5. Попробуем протестить на нагрузку.
6. Попробуем но нагрузка.
7. Да будет блядь.
8. Попробуем реализовать.
9. Хз.
10. Ты представь 90 человек с фонариками. Сервер ляжет.
11. Я еще раз говорю если бы сделали то по нормальному а не через твои кривые способы.
_________________________________
Когда все идеи будут выполнены/отклонены мы напишем в данную тему. Апдейты в новую тему пиши.
