### ISSUE TITLE
Идеи

### ISSUE THREAD

**Issue by Seopyx** [bossobeboss/newmetro#2]
1. Добавьте All+E чтобы сесть 
2. Добавьте в Кл и рейх Класс например: Тяжёлый пулеметчик он будет в броне медленным и допустим с оружие у кл Дшк у Рейха Гатлинг ( ну ли на ваш выбор)
3. Сделайте вес у оружия и предметов в инвентаре чтобы человек не мог в инвентаре нести 11 Гатлингов 
4.Добавте Газ в определённых местах в метро 
5. Сделайте чтобы когда у тебя остаётся мало хп у тебя например темнел экран и менялся звук
6. Предмет верёвку или наручники чтобы связывать руки
7. Добавить Профу Сталкер (Желательно с гитаркой)

**Comment by Gribnik228** [comment]
http://steamcommunity.com/profiles/76561198147097043/myworkshopfiles/?appid=4000&browsefilter=mysubscriptions

**Comment by Gribnik228** [comment]
Добавить вот это пистолет,за донат,с бронебойными патронами
http://steamcommunity.com/sharedfiles/filedetails/?id=950465972

**Comment by bossobeboss** [comment]
1. Да
2. Думаем да
3. Попробуем
4. Будет. И на поверхности будет.
5. Однозначно будет.
6. Думаем да.

______________
Когда все идеи будут выполнены/отклонены мы напишем в данную тему
