### ISSUE TITLE
Идеи от человека

### ISSUE THREAD

**Issue by Crazynik344** [bossobeboss/newmetro#3]
1.Добавить кастомизацию персонажа в метро-пример (Человек только что вышел со своей станции и он нашел шапку,очки,сигареты и так далее, мог взаимодействовать с этими предметами.

2.Уложиться больше в реализм- добавить жажду,голод,тепло тела,выносливость.

3.Можно еще добавить взаимодействие с открытым миром (взять тумбочку разломать ее на доски и потом разжечь костер чтобы не было холодно.

4.Сделать навыки для персонажа по типу силы,ловкости,выносливости,интеллекта (например чтобы скрафтить что-нибудь нужен хороший интеллект и сила,чтобы перепрыгнуть препятствие или убежать от кого-то нужна хорошая выносливость.

5.Можно добавить маскировочные костюмы, при их одевании у тебя будет скин одной из фракции и поменяется цвет ника чтобы не было метагейминга.

6.Добавить реалистичное поведение оружия или взаимодействие с ним(как в fallout 4-Например если добавить некоторые компоненты и добавить их в ублюдку можно сделать на нем прицел, приделать глушитель,уменьшить отдачу итд.

7.Добавить больше гаджетов чтобы человеку легче было выполнять работу (примеры-Дроны,Ipod,Iphone(телефоны)) итд

Идеи будут добавляться

**Comment by bossobeboss** [comment]
Мы подумаем над этими идеями

_______________________

Когда все идеи будут выполнены/отклонены мы напишем в данную тему
