### ISSUE TITLE
Идеи от Васеньки Открывашечки(P.S. Walkie - грайм волчара, брррре)

### ISSUE THREAD

**Issue by VasyaOtcryvashka** [bossobeboss/newmetro#4]
1. Хорошенько поработать над правилами сервера и над наказаниями за их нарушение. На данный момент чуть ли не каждую минуту возникают спорные моменты, хотелось бы от них избавиться.(В принципе, у меня сейчас есть свободное время, могу подумать и предоставить свой вариант)
2. Поменять место станций Спарты и Ганзы. (не между собой)По поводу Спарты - какое болото?) Карл, КАКОЕ БОЛОТО ДЛЯ СПАРТЫ?)))) По поводу Ганзы, на данный момент можно сказать, что это "вымершая" станция. Туда почти никто не ходит, с ними почти никто не воюет. Также, неплохо было бы добавить еще 1 станцию с ее жителями и смотрителями.
3. Подсмотрел идею Грэнта насчет джаггернаутов. Да, нужно сделать по 1 сильному бойцу для каждой станции. Но доступ к нему - только донат. Вот так вот. И никакой брони смотрителям! Оружие у них оставить то же, ублюдки! Какие калаши, смотрители люди небогатые.
4. А вот Спарте броню просто необходимо добавить. Во первых, чтобы не портить внешний вид рейнджера, потому как хочется ходить в броне, но со стандартным скином. Во вторых, это сделает рейнджера чуть сильнее, по сравнению с другими обитателями метро.
5. Обновить гитару, мб сделать даже несколько гитар, с разной музыкой и разной стоимостью.

На данный момент это пока что весь список идей, впоследствии он будет дополняться. Ваш Вася Открывашка^^

**Comment by bossobeboss** [comment]
1. Да поработаем.
2. Без комментариев
3. Думаю да
4. Да
5. Мб да.
_______________________

Когда все идеи будут выполнены/отклонены мы напишем в данную тему
