### ISSUE TITLE
NEW идеи

### ISSUE THREAD

**Issue by kirill42123** [bossobeboss/newmetro#5]
1. добавить РП профы мутантов и создать строгие правила для них. (сделать их донатными)
2. добавить тени либо в виде РП профы либо в виде НПС.
3. сделать побольше места остановок (с костром) около которых будут либо НПС либо трупы с лутом.
4. сделать нормальные мерки оружия, ибо у гатлинга от 1 лица это укороченное что-то, а с боку это нормальный гатлинг.
5. добавить больше оружия, меньше донатного, например как из трейлера "Metro Exodus".
6. изменить цены в донат шопе например того же "АКС-74У облегченный" ибо то что стреляет очередями неиграбельное, тот же ашот, когда это однозарядный дробовик стал стоить дороже мощного оружия с 45 патрами ?
7. починить сетевой код, ибо я не понимаю как я стреляю в тело а убиваю с 1 выстрела или же стреляю в голову а у врага 0 эмоций, а пуля наверное с краской была.

возможно дополнение ... Please Wait ...

**Comment by bossobeboss** [comment]
1. Думаю да
2. ХЗ
3. Однозначно
4. Передадим Уриелу
5. Возможно. Передадим Уриелу.
6. Цены изменим.
7. Думаю все будет лучше
_______________________

Когда все идеи будут выполнены/отклонены мы напишем в данную тему
