### ISSUE TITLE
Новые идеи 

### ISSUE THREAD

**Issue by MRWarwolk** [bossobeboss/newmetro#6]
1.**Оружие** 
0.1-Сделайте оружию прочность, если оно долго использовались его нужно ремонтировать.
0.2-Добавьте возможность выбирать между патронами (Бронебойные и тд)
0.3-Сделайте все оружие  дорогим но жестким, чтобы игроки жили на ВДНХ и пытались заработать себе на хлеб там, только потом могли покинуть станцию, а то каждый школьник пишет в профу (СУПИР УБИЦА(НАЕМ)) 
2. **Профы**
0.1-Добавьте вместо проф(Наемник и тд) профы жителей станций (К.Л; 4рейха и тд)
0.2-Сделайте одну профу для JOB, зачем добавлять кучу лишних проф, когда можно сделать одну, но так чтобы игрок был волен выбирать что-то своё. Для метро JOB это необходимое. 
0.3-Сделайте некоторые профы за донат или за квенту. 
0.4-Добавить профы мутантов и правила для них
0.5-Изменить модельки 4рейху и КЛ
0.5-Добавить тяжелых бойцов в группировки 
0.7-Убрать экзакостюмы, понимаю найти годный модели трудно. 
3.**Гемплей**. Я знаю ваш проект, а также ваши взгляды, но прошу, некоторые из них необходимы для атмосферы.
0.1-Жажда и голод.
0.2-Возможность делать свою еду
0.3-Патроны должны добываться потом и кровью
0.4-Гитара, просьба сделать список всех песен, а также добавить больше. 
0.5-Охота, также возможность добывать: Ткань, металл и тд самому. 
4. **РП!**
0.1-Наркоту!
0.2-Сделать фронт Красной Линии и 4 Рейху 
0.3-Стяжки или верёвки, чтобы возможность была связывать игроков
0.4-Добавить возможность оглушить игрока, КАК ЭТО СДЕЛАТЬ!? Просто, связываем и начинаем 
наносить удар, типа как загрузка при надевание наручников, только тебя кидает в редголл.
0.5-возможность крафта своих пуль для оружия. 
0.6-Кастомизация персонажа, а также УБЕРИТЕ НЕГРОВ!!!
0.7-Описание персонажа (Тело Вяски было как у аполлона) 
5. ....
P.S. 
Я понимаю что некоторые идеи не пойдут проекту из-за того, что донатить не будут. НО, это всего навсего идеи.

**Comment by bossobeboss** [comment]
1.2 точно
1.3 цены изменятся
2.1 будут
2.2 не совсем
2.3 профы за донат будут. и полис будет по квенте
2.4 в августе думаю черных добавим
2.5 думаю да
2.7 поставим годные модели
3.1 голод однозначно жажда возможно
3.2 да
3.3 сменим ценовую политику
3.4 добавим песен думаю
3.5 да-да
4.1 думаю да
4.2 да
4.3 да
4.4 будут баги. цэ гмод...
4.5 мб
4.6 в метро вполне могли быть негры-иммигранты
4.7 Ой хз хз

**Comment by bossobeboss** [comment]
То что не ответил в рассмотрении
_______________________

Когда все идеи будут выполнены/отклонены мы напишем в данную тему
