### ISSUE TITLE
Идеи #2

### ISSUE THREAD

**Issue by NicholayGrant** [bossobeboss/newmetro#8]
1)Убрать экзоскелеты и заменить их на нормальные скины с броней.
2)Сделать больше раз взлома дверей дробовиком.
3)Сделать новые станции.
4)Добавить больше оружия, больше брони у торговца.
5)Добавь шкалу усталости, т.к у Вас бесконечно бегай.
6)Сменить название - "Упырь > Падонок", т.к это модификация, или, убрать это вообще и сделать систему модификаций ,которые надо находить(реальная редкость) или крафтить.
7)Будет поверхность - будут фильтры. Предлагаю "смотреть" на таймер, с помощью кнопки, а не иконки с секундами на экране, после если в инвентаре оказался ещё 1 фильтр, с помощью инвентаря заменить его. 
8)Восстановление брони. - Идет стрельба, пуля может попасть в шлем, и после чего разломаться, т.к до этого с ним например что-то делали и он был ненадежный, вернувшись на базу, подходишь например к NPC/реал человеку и говоришь - Слушай, у меня шлем тут сломался, сваргань новый. С помощью манипуляций, он подбирает шлем и когда была броня 99 - становится 110.
9)Заменить систему лута и инвентаря. Например, когда наводишь на предмет, зажав кнопку, ты читаешь его описание и есть ли там хоть что-то, например "Масло", почитав описание, оно оказывается пустым и пишет "Пустой флакон с маслом, можно пополнить".
10)Взлом двери с помощью ноги. Если человек специально запер дверь, а у тебя последний патрон, при хорошем ударе, ты берешь и нажав на кнопку пару раз(с таймингом), ломаешь дверь.
11)Обновить полностью карту, добавить свои ходы (HAMMER Editor), и так далее, добавить новые обьекты, помимо этих  PermaPror и поверхности.
12)Добавить броне-дверь и вообще возможность "приватить" территории. Купил у торговца обычную или броне-дверь, после чего выбираешь место где хочешь её поставить. (Строго в обозначенных местах, т.е где заскриптовано), и эту дверь может открывать хозяин и владельцы, у которых есть ключи, чтобы люди не кричали "ПРОП БЛООООК".
13) Поменять станции, добавить новые обьекты и здания для торговли и жил. площади.
14) От 1 попадания дверь дробовиком, она не сломается, может только дырка появится и все. Предлагаю увеличить кол-во стрельбы в дверь, дабы она сломалась.
15) Предлагаю сделать человека немного трусливым. Если человек впервые стреляет (Что возможно после обновы), то он может не выстрелить и будут звуки "Я не могу, боюсь", или что-то типо этого, ведь не каждый человек способен стрелять, ведь тоже боится.
16) Осечки - автомат долго стреляет, перегревается и случаются осечки, после чего надо просто передернуть эту.
17) Люди любят строить базы, но зачем эти перма-проп, когда можно сделать систему своей постройки, люди не тратят деньги. когда на материал уходят много денег, надо готовится ведь к этому.

**Comment by NicholayGrant** [comment]
Добавление к 17 пунтку. 
Теперь будет меньше тупых фрак , ведь им нужна будет база, а для постройки деньги.
Добавление к 12 пункту. Для так сказать привата, надопоговорить с нач.станции, после подойдя к месту, через с выбирает место и ник игрока и ставит цену в патронах. СТРОГО БЕЗ ДОНАТА Т.К ПОСЛЕ ПЕРЕЗАХОДА МЕСТО СРАЗУ СТАНОВИТСЯ СВОБОДНЫМ

**Comment by ChehovLT** [comment]
Хочу добавить к идеям Грэнта скрины тяжелых бойцов разных Фракция.Таких как:
http://steamcommunity.com/sharedfiles/filedetails/?id=973565341 - ВДНХ Джаггернаут
http://steamcommunity.com/sharedfiles/filedetails/?id=973564892 - Тяжеловооруженный Боец Железного Легиона

**Comment by bossobeboss** [comment]
Многие идеи годные. Будем заглядывать сюда при разработке.
_______________________

Когда все идеи будут выполнены/отклонены мы напишем в данную тему
