### ISSUE TITLE
Идея об экономике.

### ISSUE THREAD

**Issue by VasiliiKaifat** [bossobeboss/newmetro#9]
Вероятно об этом писали но все же.
1)Добавьте разницу цен между станциями,на 1.1
ВДНХ сделайте дешевой еду и только ,все остальное по запредельным ценам ,тк по лору она только это и производила.
1.2 на ганзе (если она будет)  сделайте некоторое оружие дешевым-падонок ,двустволку,ублюдок,ак 74,1-2 костюма,дробь и пистолетные патроны.
1.3 на рейхе сделайте дешевое снайперское оружие-свк,вентиль,винтовку с бронебойными патронами(забыл как называется ),1-2 костюма,патроны снайперские.
1.4 На кл -штурмовой автомат,калаш с обвесами,аксу 74, 1-2 брони,патроны под автоматы.
1.5 На полисе -дешевый противогаз,фильтр ,сталкерские костюмы и аптечку()
Вооот

**Comment by VasiliiKaifat** [comment]
(Дополнение)
1.5сделайте дешёвые калаши 2012 и всв у спарты
1.6 у бандитов дешёвый мушкет,упырь,револьвер.

**Comment by NicholayGrant** [comment]
На сервере один бот с одними ценами, по сути, это надо писать нового бота который торгует другим оружием и так далее. Но я за...

**Comment by bossobeboss** [comment]
Да без б ваще

**Comment by bossobeboss** [comment]
Сделаем мы новых ботов. Ето же изи. КФГ настроить...
